Fix errors caused by SuperTableBlockElement.eagerLoadingMap()
Invalid use of ArrayHelper.index generates the following error:
```
Internal Server Error
Too few arguments to function yii\helpers\BaseArrayHelper::index(), 1 passed in vendor/verbb/super-table/src/elements/SuperTableBlockElement.php on line 83 and at least 2 expected
```
$fieldHandle is not declared (it appears to be a typo).